services:
  - type: web
    name: interior-design-frontend
    env: static
    buildCommand: npm run build:render
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com
        sync: false
      - key: NODE_ENV
        value: production
        sync: false
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
      - type: rewrite
        source: /favicon.ico
        destination: /favicon.ico
      - type: rewrite
        source: /manifest.json
        destination: /manifest.json
      - type: rewrite
        source: /logo*.png
        destination: /logo*.png
      - type: rewrite
        source: /*
        destination: /index.html
